### ISSUE TITLE
get different answers to Python Numpy routines

### ISSUE THREAD

**Issue by DWAWOOD** [YoichiroUrita/Math#2] opened 2024-12-02 18:38 UTC
I have got both your codes for Eigenvalues /Eigen vectors to work in VBA and would like to use them in Excel. However the same input they generate quite different rerslts to tthe Python Numpy Linear algebra routines. Even if I input Eigenvalues generated by Numpy into your code the Eigenvectors generated are different for the same input matrix. I wonder if you could comment on this. I can send an example if you would like to explore /explain why.
Kind regards
David Wood
dw@dwasolutions.com

**Comment by YoichiroUrita** [comment] 2024-12-03 02:27
Thank you for message.
Interesting.
Can I have your matrix that generated different results.
From my experience, I guess, If the matrix's determinant is zero or almost zero, numpy might add/switch stable routine like SVD.
So that cause genarete quite different Eigenvalues and Eigen vectors from theoretic resolve.

**Comment by DWAWOOD** [comment] 2024-12-03 10:41
Dear Yoichira, 

Thank you for your prompt response. Please see attached an Excel file with an example 6by6 matrix with the VBA results and the numpy code used and its results.

 

I am probably doing something wrong? But using the numpy  complex eigenvectors with your complex number routine I thought should provide comparable results?

 

Do you have a VBA routine that generates the complex number eigenvectors. If so, it would be worth comparing those with the numpy ones. Also, I would be interested in that code, if you are able to share it.

 

I look forward to hearing from you.

Kind regards,

David

**Comment by DWAWOOD** [comment] 2024-12-03 10:45
I meant in the last paragraph:

Do you have a VBA routine that generates the complex number eigenvalues. If so, it would be worth comparing those with the numpy ones. Also, I would be interested in that code, if you are able to share it.

**Comment by YoichiroUrita** [comment] 2024-12-03 15:27
I have not recieved attached excel file.
(Probably size limit or  some security policy for xlsm files.)

Well, I have thought that you ask eigenvalues problem with symmetric matrix.
Have you tried my 'SingleShiftQRforComplexEigenProblem.vba'?
In complex eigenvalues, it's hard to solve and unstable to solve.
For example, Nastran and Matlab generate different complex eigenvalues and complex eigenvectors with same non-symmetric matrix.
Unfortunately my routine is less stable than commercial ones.

Complex eigenvalue problems are generally said to be like art. That makes it difficult to generate eigenvalues.

**Comment by YoichiroUrita** [comment] 2024-12-03 15:34
By the way, Numpy use LAPACK（Linear Algebra PACKage）written by FORTRAN.
That's same as MATLAB and Scilab.
So, I guess those generate same complex eigenvalues and complex eigenvectors with same non-symmetric matrix.

**Comment by DWAWOOD** [comment] 2024-12-03 17:56
I tried the two codes from your Github site and concentrated on the second one for complex eigenvectors. However, that code did not generate its own eigen values. Does your SingleShiftQRforComplexEigenProblem.vba file also generate eigen values? If so, I have not seen that, Please provide a link if possible.

 

I would like to send you some of the details I had included in the spreadsheet you did not receive. I could resend that  sheet to you if you have an e-mail contact I can use?

One of the matrices I tried is as follows:


1

3

5

7

6

4


0.33

1

4

6

5

3


0.2

0.25

1

3

2

0.5


0.14

0.17

0.33

1

0.5

0.25


0.17

0.2

0.5

2

1

0.33


0.25

0.33

2

4

3

1

Using the complex eigenvectors from numpy as input:


real component

	6.228

0.034

0.034

-0.121

-0.121

-0.054


complex component J

	0

1.178

-1.178

0.215

-0.215

0

Your complex VBA code calculated the following eigen vectors:


1.0000

0.592

0.19

0.084

0.124

0.293

0

0

0

0

0

0


1.0000

0.401

-0.122

-0.019

-0.081

-0.076

-0.542

0.438

0.063

-0.077

-0.041

0.215


1.0000

0.401

-0.122

-0.019

-0.081

0.076

0.542

-0.438

-0.063

0.077

0.041

-0.215


1.0000

-0.248

0.228

-0.144

0.082

-0.21

-0.736

0.568

-0.093

7E-04

0.146

-0.269


1.0000

-0.248

0.228

-0.144

0.082

0.21

0.736

-0.568

0.093

-7E-04

-0.146

0.269


1.0000

-0.438

-0.437

-0.2

0.391

0.374

0

0

0

0

0

0

Perhaps you could check that your code generates these answers or whether I have done something wrong

Kind regards,

David

**Comment by DWAWOOD** [comment] 2024-12-03 18:00
Yes ,I believe that is the case. Although it is easy to use one of these packages, I am keen to also do this in VBA so results can be integrated into a spreadsheet analysis. Hence, my interest in your codes

**Comment by YoichiroUrita** [comment] 2024-12-04 04:13
In this case.

Sample matrix (your matrix)
|col1|col2|col3|col4|col5|col6|
|---:|---:|---:|---:|---:|---:|
|1|0.33|0.2|0.14|0.17|0.25|
|3|1|0.25|0.17|0.2|0.33|
|5|4|1|0.33|0.5|2|
|7|6|3|1|2|4|
|6|5|2|0.5|1|3|
|4|3|0.5|0.25|0.33|1|

numpy's eigenvalues
| |1st|2nd|3rd|4th|5th|6th|
|---:|---:|---:|---:|---:|---:|---:|
|Real|6.22829414|0.0340523|0.0340523|-0.12133703|-0.12133703|-0.05372468|
|Imag|0|1.17769078|-1.17769078|0.21492734|-0.21492734|0|


so, transform to Hessenberg matrix by [HouseholderTransformation.vba](https://github.com/YoichiroUrita/Math/blob/master/HouseholderTransformation.vba)
|col1|col2|col3|col4|col5|col6|
|---:|---:|---:|---:|---:|---:|
|1|-0.429470819946111|-0.253263240500835|0.105244901856363|-0.00125577590261929|0.0153127230092574|
|-11.6189500386223|7.46185185185185|7.68754235293053|-3.92331467332806|0.369424250612218|-0.235684556182195|
|0|-2.14545883383526|-1.43047618702462|-0.187960161193595|0.258857577056203|0.0372027608411887|
|0|0|0.704114303966875|-0.680982753655666|-0.0395101500579577|-0.0638133926154999|
|0|0|0|0.323776326595301|-0.259729584857359|0.0448852834801184|
|0|0|0|0|-0.0893935046695999|-0.0906633263142012|

Exist eigenvalues from this Hessenberg matrix by [SingleShiftQRforComplexEigenProblem.vba](https://github.com/YoichiroUrita/Math/blob/master/SingleShiftQRforComplexEigenProblem.vba)
| |1st|2nd|3rd|4th|5th|6th|
|---:|---:|---:|---:|---:|---:|---:|
|Real|6.22829413798717|6.25403295327484|10.2973118345671|4.6085005470747|-3.94119898225549|6.32104327822844|
|Imag|0|0.048412070636581|2.48280061612394|1.28170097572501|-1.07127264579928|1.68069707000716|

It seems quite different above 2nd eigenvalue.
This might be  affected by convergence and initial conditions.
This requires modification of the algorithm, but it is a fairly difficult problem.

**Comment by DWAWOOD** [comment] 2024-12-04 07:11
Thank you for your response and time. I will try to use the two other codes
you have mentioned.

Does this mean that you recommend that all non-symmetrical matrices should
be transformed to a Hessenberg matrix before calculating eigenvalues with
the singleshiftQR?

**Comment by YoichiroUrita** [comment] 2024-12-04 11:53
Basically, in eigenvalues problem with small sized non-symmetric matrix,
scheme to solve is as below
1. Transform to Hessenberg matrix
2. Exist eigenvalues by some QR algorithm (doubleQR,singleQR etc)
3. Exist eigenvectors by Gausse elimination

**Comment by DWAWOOD** [comment] 2024-12-04 12:52
Thank you.

**Comment by YoichiroUrita** [comment] 2024-12-04 13:25
QR algorithm makes upper-right-triangular matrix and exist eigenvalues from upper-right-triangular matrix by diagonal 2*2 blocks with solution formula.
In usual, original matrix (the matrix which you want to solve) is far from upper-right-triangluar matrix.
So, transforming to Hessenberg matrix is needed for calcuration cost lower and make solution stably.

LAPACK( in this case, it might be used DGEEV function which is for non-symmetric eigenvalue problem) is almost same as above, but it is including scaling, balancing and some more stable technics.

**Comment by DWAWOOD** [comment] 2024-12-04 16:11
Thank you for that additional information, that probably explains the slightly different results (vba versus numpy). Do you have plans to eventually introduce scaling, balancing and stabilization features to your SingleShiftQRforComplexEigenProblem.vba algorithm?

**Comment by YoichiroUrita** [comment] 2024-12-04 20:24
Unfortunately, there are no plans at the moment.

**Comment by YoichiroUrita** [comment] 2024-12-05 14:34
I just reminded very important things.
The single-shift QR algorithm can not generate complex conjugate eigenvalues.
So, this causes quite different result about conjugated eigenvalue.
For example,In LAPACK, If program found complex conjugate eigenvalues in iteration loop, algorithm must switch to double-shift QR .
Unfortunaly, my function does not have switch.
This is the main reason why the result was different.

**Comment by DWAWOOD** [comment] 2024-12-05 15:44
Thanks for that information. Does that mean it might be better as a matter of routine for non-symmetrical matrices to use the procedure?

1.	Transform to Hessenberg matrix
2.	Derive eigenvalues with double QR algorithm
3.	Derive eigenvectors with Gauss elimination algorithm

Even if the solution derived  does not involve complex conjugate eigenvalues?

Also, what do you consider to be the approximate size limit for a “small” non-symmetrical matrix?

**Comment by YoichiroUrita** [comment] 2024-12-05 23:06
No, the QR algorithm must include both single and double and be able to switch repeatedly depending on the situation.
If there are only singles, the conjugate pair cannot be derived.
On the other hand, double has the disadvantage that it can only solve matrices of even size.

**Comment by DWAWOOD** [comment] 2024-12-06 12:42
Thanks for that clarification

**Comment by YoichiroUrita** [comment] 2024-12-06 14:25
Good news.
If you use a library called ALGLIB, you can solve the eigenvalues ​​of an asymmetric matrix in Excel.
Currently under investigation.
The test calculation has been completed.
Although it is in Japanese, it describes how to install it. Please read with browser's translation.
https://rm-engineering.info/wordpress/excel%e3%81%a7%e6%95%b0%e5%80%a4%e8%a8%88%e7%ae%97%ef%bd%9ealglib%e3%81%ae%e5%b0%8e%e5%85%a5%ef%bd%9e/#toc12

**Comment by DWAWOOD** [comment] 2024-12-06 16:11
Thank you. I have downloaded the AlgLib package and identified the  evd.bas file as the one with several eigen algorithms. I will try to work with this.

**Comment by DWAWOOD** [comment] 2024-12-06 18:30
I have installed the AlgLib evd.bas as a module in my Excel workbook

But I am struggling to get it to work on a command from the worksheet

The matrix I sent you is in cells B2:G7 of the work sheet

When I try to call the Public Function RMatrixEVD from that Excel sheet with the command

=RMatrixEVD($B$2:$G$7,6,3)    where 6 is the entry for N (size of matrix) and 3 is the flag (Z) for the output

I get =#NAME?

Am I doing anything obviously wrong? Do I need to add more instructions in that call command (eg., where the output should be placed?  AlgLib does not provide easy user instructions for calling their functions

**Comment by YoichiroUrita** [comment] 2024-12-07 00:06
>Am I doing anything obviously wrong?

Unfortunately,Yes.

Generally, you cannot call macros from cells.
Therefore, we need to make user function to pass information to the macro function (in this case, RMatrixEVD)  from cells.

**Comment by DWAWOOD** [comment] 2024-12-07 06:57
OK. I have created a sub that reads in the matrix and calls the RMatrixEVD macro function but it still does not work.

I have placed my sub in the Workbook Module that contains all the EVD function codes

This is the first time I have used AlgLib and there is no instructions or examples provided for setting it up. So I am probably not doing it right.

The error I get is “User-defined type not defined” and it highlights code in the AlgLib Library of a function I have not directly called (Presumably my call to RMatrixEVD has called that other function and my input is not sufficient?)

The code I have written firstly reads in the matrix as variable X  (Dim as Double) with matrix size of 6 as variable nn (Dim as Long).  The index of X I have created is 0 to N-1 as that seems to be required.

I assume that I have to specify and dim an array for the output? 

Dim XX As Double ‘ this is for output of EigenValues only?

Call RMatrixEVD(X, nn, 0, XX) ‘ the 0 sets the function to calculate EigenValues only (as an initial test)

‘ My intention is then to print the output from the sub to a specified part of the worksheet (if I can get it to work

‘My printing  command  assumes that the function places it answer in matrix XX

For AA = 0 To N

Cells(2 + AA, 12).Value = XX(AA)

Next AA

The call to RMatrixEVD fails with the error:

“User-defined type not defined” and highlights the HMatrixEVD function?

Is there some generic VBA setup for calling AlgLib functions and getting their results printed to a worksheet? 

I prefer to use a sub than a function so I can print the answer components to different parts of the spreadsheet, when I get it to work

Any guidance would be welcome. Perhaps there is a website with a basic tutorial or video explaining how to call Alglib functions correctly from VBA?

**Comment by YoichiroUrita** [comment] 2024-12-07 15:08
First of all,I just have used ALGLIB yesterday too, so my experience term with ALGLIB is almost same as you.

Hard to advice cause I haven't seen your whole code.

I recommend you practice more easy problem about VBA like basic leaning contents at least about cast, If you could not fix this error in yourself.
Or good to use Stackoverflow.

It seems that error occurred by 2 reasons at least.

1. Misstook array declear.

NG:
Dim XX as double <- this declare is for variable

Correct:
Dim XX() as double <- this declare is for array

2.Not imported neccesary bas files.(Probably)

You need import not only evd.bas also ap.bas, blas.bas, hsschur.bas, reflections.bas, rotations.bas.
Check my table on article.

**Comment by DWAWOOD** [comment] 2024-12-07 18:27
I have not solved the problem. However, I found this website which was helpful regarding setting up the interface to the AlgLib functions:

https://newtonexcelbach.com/2010/05/20/installing-alglib-with-excel-vba/

I followed that recommended setup for the EVD Eigenvalue and eigenvector  RMatrixEVD function but I still got the same error.  That error is User type not defined. And it highlights the HMatrix… functions in the EVD module. When I look at these, I see they contain input data type requirements of “As Complex”. VBA does not recognise a Complex data type, and I think that is the problem? I tried to modify those datatypes to Double but VBA would not accept the changes I tried.

 

Please check you EVD module and see if there are also Complex data types specified? Perhaps the version I have downloaded is not the right one?

 

Have you actually managed to get SMatrixEVD or RMatrixDVD functions in AlgLib to work?

 

It seems to me that this package of codes is quite old (pre-2010) and in VB6 some of which is not compatible with the current versions of VBA? Probably the code could be extracted and modified from the various functions used to make it work, but that would take too much time.

**Comment by YoichiroUrita** [comment] 2024-12-08 02:25
To be honest, I don't know how much programming or VBA background you have, so I can't give you accurate advice.
Also, I don't understand the entire code you are trying to run.

**Please tell me about these things.**

1.  **The code you are trying to run**(Can I have your entire code?)
2. **Imported .bas files you installed to worksheet**
3.  Did you run the sample program on my site? And what about the results?
4. How much programming experience do you have?
5. (Since you are using numpy, you should be able to use python to some extent.)
6. How much experience do you have with VBA?

If there is an error with the **'Complex data types specified', it means that ap.bas has not been imported.**
**As I pointed out last time, let's import the necessary files.**
If you don't understand what I'm saying, please be specific about what you don't understand.

If you are new to VBA or linear algebra programming, **DO NOT RUSH and solve the problem STEP-BY-STEP.**

**Comment by DWAWOOD** [comment] 2024-12-08 10:10
Answer to Q1

My unsuccessful code so far

Worksheets("AlgEig").Select

'Enter dimension of matrix

Dim nn As Long

nn = 6

'Read in Data (square matrix with real positive numbers)

Dim InData(20, 20) As Variant

Dim X(20, 20) As Double

For AA = 1 To nn

For BB = 1 To nn

InData(AA, BB) = Cells(1 + AA, 2 + BB).Value

X(AA, BB) = InData(AA, BB)

Next BB

Next AA

'

'Following section of code adapted from:

'https://newtonexcelbach.com/2010/05/20/installing-alglib-with-excel-vba/

'This was used because there are no useful instructions on the AlgLib site!

Dim N As Long, M As Long, D() As Double, Z() As Double, IsUpper() As Boolean, ResA() As Double, Res() As Boolean

Dim A2() As Double, I As Long, J As Long, K As Long, WR() As Double, WI() As Double, VL() As Double, VR() As Double

Dim Vect As Long

M = UBound(X)

N = UBound(X, 2)

Vect = 0 ‘ as a first try I am setting this to eigenvalues only

ReDim A2(0 To M - 1, 0 To N - 1)

'Converts input matrix X to a 0 to N-1 index in matrix A2

For I = 1 To M

    For J = 1 To N

      A2(I - 1, J - 1) = X(I, J)

    Next J

Next I

'Call the relevant EVD function

Res = RMatrixEVD(A2, M, Vect, WR, WI, VL, VR)

‘ the code fails at the above command here with compile error: can’t assign to array

        If Res = True Then

  If Vect = 0 Then ReDim ResA(1 To 2, 1 To M) Else ReDim ResA(1 To M * 2 + 2, 1 To M)

  For I = 0 To M - 1

  ResA(1, I + 1) = WR(I)

  ResA(2, I + 1) = WI(I)

  Next I

  If Vect = 0 Then

  EigenvR = ResA

            GoTo Last:

        End If

  If Vect = 1 Or Vect = 3 Then

  For I = 0 To M - 1

                For J = 0 To M - 1

  ResA(I + 3, J + 1) = VR(I, J)

                Next J

  Next I

        End If

  If Vect = 2 Or Vect = 3 Then

  For I = 0 To M - 1

                For J = 0 To M - 1

  ResA(I + M + 3, J + 1) = VL(I, J)

                Next J

  Next I

        End If

  EigenvR = ResA

    Else

  EigenvR = "Did not converge"

    End If

Last:

'Print Outputs

'Print EigenValues

For AA = 0 To M - 1

Cells(2 + AA, 12).Value = WR(AA) 'EigenValue Real component

Cells(2 + AA, 13).Value = WI(AA) 'EigenValue imaginary component

Next AA

End Sub

**Comment by DWAWOOD** [comment] 2024-12-08 10:12
Answer Q2: 

ap

reflections

creflections

hqrnd

matgen

matinv

ablasf

ablas

trfac

trlinsolve

safesolve

rcond

evd

hblas

hsschur

ortfac

rotations

sblas

[but there are no instructions on AlgLib site about which are required!!!]

**Comment by DWAWOOD** [comment] 2024-12-08 10:15
Answer Q3

I sent you my initial results, but I have not yet run the three stage procedure as what I am ideally looking for is a single step VBA solution.  When you sent the link to Alglib I switched my attention to the that  as I had hoped Alglib would provide that

**Comment by DWAWOOD** [comment] 2024-12-08 10:19
Q4:

I have 25 years of VBA experience and 10 years of python experience and have generated some useful codes in that period for a range of scientific problems. However, I am an intermittent and self-taught user of both. I typically make mistakes when I start with new codes.  I am an extensive user of suggestion from stackoverflow, github and Kaggle. I note there is very little online regarding Alglib problems and most of the posts are 2010 or earlier.  The package appears not to be actively maintained and its documentation is dreadful

**Comment by DWAWOOD** [comment] 2024-12-08 10:22
Q5. Although Python is clearly superior (and about 1000x quicker to set up!) than VBA for this task, I had hoped to be able to use both to provide complementary information in a spreadsheet with VBA providing more transparency and an alternative verification

**Comment by DWAWOOD** [comment] 2024-12-08 10:23
Ans Q6. About 25 years with some linear / matrix algebra. But I have not used it for eigenvalues/eigenvectors before. Hence the reason why I am looking for efficient VBA code

**Comment by YoichiroUrita** [comment] 2024-12-08 14:06
What I am asking about in Q3 is what the results of the ALGLIB sample program below were.
https://rm-engineering.info/wordpress/excel%e3%81%a7%e6%95%b0%e5%80%a4%e8%a8%88%e7%ae%97%ef%bd%9ealglib%e3%81%ae%e5%b0%8e%e5%85%a5%ef%bd%9e/#toc12

I don't want to write something like this, but since you are NOT a beginner, please forgive me for writing something harsh.

I have a hard time understanding why you asked so many fragmented questions, even though you have so much experience.
You say that you regularly use Stackoverflow, etc., but the person asking the question has provided his own source code and written down how the error occurred, right?

You can understand that I am devoting significant time resources to this.
Please check again to see if your comments on this GitHub thread are legible.
https://github.com/YoichiroUrita/Math/issues/2
Github is not just a space for you and me. Others may also view this thread for reference.
Please reconsider whether the comment you posted is easy to read when viewed from that perspective.
And please make corrections if necessary.
For example, is it necessary to include the preamble as is?
Are you saving time and effort by simply communicating via email?
For example, why don't you try pasting your code into your GitHub and linking it?
I will revise this comment if you would like to revise the previous comment to make it easier to read.
I hope you make the right decision.
Please think from the perspective of the respondent or Others.
These are good manners, regardless of your depth of experience, right?

The source code presented this time also seems to be missing the first line. 
There is no way to reproduce this here.
Is it a subroutine? Is it a function?
What are the arguments?
This will make it easier to understand what you want to do and what should I fix.

Not related to the error, but why are you using sizes M and N when you know it's a square matrix?

‘ the code fails at the above command here with compile error: can’t assign to array
Which array is this comment out about?

Judging from the answer to Q2, ablas.bas, sblas.bas, etc. are included instead of the required blas.bas being imported.
Many unnecessary files are also imported.
https://newtonexcelbach.com/2010/05/20/installing-alglib-with-excel-vba/
It seems different from this article, but what made you import these files?


I'm also self-taught and do programming on my own, so I have far less experience than you. 
My main job is a mechanical engineer and I have almost never used python.
Don't get nervous and rush.

**Comment by YoichiroUrita** [comment] 2024-12-08 14:31
Addendum
Why did you declare Res as an array?
Even though you are determining Res=0 in the If statement?
Isn't this the reason for 'can't assign to array'?
I wonder how you can't solve such a basic error even though you have 25 years of VBA experience.

**Comment by DWAWOOD** [comment] 2024-12-08 16:19
The two tips you have given me today have helped to get the code to work for eigenvalues!

That is 1) loading  blas.bas and 2) declaring Res as a Boolean variable rather than as an array. Thank you

My interface routine produced the following results for the sample array I gave you


6.228294

0


0.034052

1.177691


0.034052

-1.17769


-0.12134

0.214927


-0.12134

-0.21493


-0.05372

0

Also, I had not seen the Alglib example on your github sitr before, so I misunderstood your Q3. Thank you for the link. Most of it is in Japanese but I will try to use it.

I really appreciate our discussion on this.  I think we have probably both spent more time on this than we should.  I will play around further but I have my doubts about using the Alglib library in the future. It is so poorly documented, that if I wanted to do some other calculations using its routines I frealise that I would have to spend hours trying to find out which packages to load (and there are very few answers for AlgLib problems at online sites. For instance, I have not managed to get a routine to work that loads all 102 packages quickly into a workbook. Have you?

**Comment by YoichiroUrita** [comment] 2024-12-09 00:13
Congratulations to fix,but...
It's a disappointing that you still post to Github via email with preamble sentences.
And, The result values is too fragmented to understand.
What is your original  matrix to solve, eigenvalues and eigenvectors?
Are you thinking from the perspective of the recipient?
Have you ever been warned by your boss or co-worker at work?
Have you ever been told that you don't have enough attention?

Maybe you are too old to use technology?
Or maybe you have a disorder such as ADHD and tend to ignore other people's conversations?
If so, I'll be patient and try to devise an approach.
Otherwise, it would be a sunk cost to have further conversations with a selfish person.

**Comment by DWAWOOD** [comment] 2024-12-09 07:25
I do not have anything further to discuss.

**Closed as completed** 2024-12-09 10:49 UTC
